apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hoge
  name: hoge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hoge
    spec:
      containers:
        - image: takemio/alpine
          name: hoge
          args: ['sh', '-c', './a.out']
      restartPolicy: Always
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: redis
#   name: redis
# spec:
#   ports:
#     - name: redis
#       port: 6379
#       targetPort: 6379
#   selector:
#     app: redis
# status:
#   loadBalancer: {}
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     app: hoge
#   name: hoge
# spec:
#     spec:
#       containers:
#         - image: takemio/alpine
#           name: hoge
#           args: ['sh', '-c', './a.out']
#       restartPolicy: Always
